# OpenPrinting IPP Virtual Scanner
#
# The generic IPP-scan scanner model.

# IPP printer attributes:
ipp.scanner = ipp.COLLECTION(
    charset_configured = ipp.CHARSET('utf-8'),
    charset_supported = ipp.CHARSET('utf-8'),
    color_supported = ipp.BOOLEAN(True),
    compression_supported = ipp.KEYWORD('none'),
    copies_default = ipp.INTEGER(1),
    copies_supported = ipp.RANGE(1,1),
    document_format_default = ipp.MIMETYPE('image/png'),
    document_format_supported = [
        ipp.MIMETYPE('image/jpeg'),
        ipp.MIMETYPE('image/png'),
    ],
    generated_natural_language_supported = ipp.LANGUAGE('en-us'),
    input_attributes_default = ipp.COLLECTION(
        input_auto_exposure = ipp.BOOLEAN(False),
        input_auto_scaling = ipp.BOOLEAN(False),
        input_auto_skew_correction = ipp.BOOLEAN(False),
        input_brightness = ipp.INTEGER(0),
        input_color_mode = ipp.KEYWORD('color'),
        input_content_type = ipp.KEYWORD('text-and-photo'),
        input_contrast = ipp.INTEGER(0),
        input_film_scan_mode = ipp.KEYWORD('not-applicable'),
        input_images_to_transfer = ipp.INTEGER(1),
        input_media = ipp.KEYWORD('iso_a4_210x297mm'),
        input_orientation_requested = ipp.ENUM(3),
        input_quality = ipp.ENUM(4),
        input_resolution = ipp.RESOLUTION(300, 300, 'dpi'),
        input_scaling_height = ipp.INTEGER(100),
        input_scaling_width = ipp.INTEGER(100),
        input_scan_regions = ipp.COLLECTION(
            x_origin = ipp.INTEGER(0),
            y_origin = ipp.INTEGER(0),
            x_dimension = ipp.INTEGER(21000),
            y_dimension = ipp.INTEGER(29700),
        ),
        input_sharpness = ipp.INTEGER(0),
        input_sides = ipp.KEYWORD('one-sided'),
        input_source = ipp.KEYWORD('platen'),
    ),
    input_attributes_supported = [
        ipp.KEYWORD('input-auto-exposure'),
        ipp.KEYWORD('input-auto-scaling'),
        ipp.KEYWORD('input-auto-skew-correction'),
        ipp.KEYWORD('input-brightness'),
        ipp.KEYWORD('input-color-mode'),
        ipp.KEYWORD('input-content-type'),
        ipp.KEYWORD('input-contrast'),
        ipp.KEYWORD('input-film-scan-mode'),
        ipp.KEYWORD('input-images-to-transfer'),
        ipp.KEYWORD('input-media'),
        ipp.KEYWORD('input-orientation-requested'),
        ipp.KEYWORD('input-quality'),
        ipp.KEYWORD('input-resolution'),
        ipp.KEYWORD('input-scaling-height'),
        ipp.KEYWORD('input-scaling-width'),
        ipp.KEYWORD('input-scan-regions'),
        ipp.KEYWORD('input-sharpness'),
        ipp.KEYWORD('input-sides'),
        ipp.KEYWORD('input-source'),
    ],
    input_color_mode_supported = [
        ipp.KEYWORD('auto'),
        ipp.KEYWORD('color'),
        ipp.KEYWORD('monochrome'),
    ],
    input_media_supported = [
        ipp.KEYWORD('iso_a4_210x297mm'),
        ipp.KEYWORD('iso_a5_148x210mm'),
        ipp.KEYWORD('iso_a6_105x148mm'),
        ipp.KEYWORD('iso_b5_176x250mm'),
        ipp.KEYWORD('na_legal_8.5x14in'),
        ipp.KEYWORD('na_letter_8.5x11in'),
        ipp.KEYWORD('na_executive_7.25x10.5in'),
        ipp.KEYWORD('na_invoice_5.5x8.5in'),
        ipp.KEYWORD('iso_c5_162x229mm'),
        ipp.KEYWORD('iso_c6_114x162mm'),
        ipp.KEYWORD('iso_dl_110x220mm'),
        ipp.KEYWORD('na_monarch_3.875x7.5in'),
        ipp.KEYWORD('jis_b5_182x257mm'),
        ipp.KEYWORD('jis_b6_128x182mm'),
        ipp.KEYWORD('jpn_you4_105x235mm'),
        ipp.KEYWORD('jpn_hagaki_100x148mm'),
        ipp.KEYWORD('jpn_oufuku_148x200mm'),
        ipp.KEYWORD('roc_16k_7.75x10.75in'),
        ipp.KEYWORD('na_foolscap_8.5x13in'),
        ipp.KEYWORD('na_number-10_4.125x9.5in'),
        ipp.KEYWORD('na_number-9_3.875x8.875in'),
        ipp.KEYWORD('na_personal_3.625x6.5in'),
        ipp.KEYWORD('om_folio_210x330mm'),
        ipp.KEYWORD('custom_max_216x356mm'),
        ipp.KEYWORD('custom_min_70x148mm'),
    ],
    input_orientation_requested_supported = [
        ipp.ENUM(3),
    ],
    input_quality_supported = [
        ipp.ENUM(3),
        ipp.ENUM(4),
        ipp.ENUM(5),
    ],
    input_resolution_supported = [
        ipp.RESOLUTION(300, 300, 'dpi'),
        ipp.RESOLUTION(600, 600, 'dpi'),
        ipp.RESOLUTION(1200, 1200, 'dpi'),
    ],
    input_scan_regions_supported = ipp.COLLECTION(
        x_origin = ipp.RANGE(0,10000),
        y_origin = ipp.RANGE(0,10000),
        x_dimension = ipp.RANGE(0,21000),
        y_dimension = ipp.RANGE(0,29700),
    ),
    input_sides_supported = [
        ipp.KEYWORD('one-sided'),
        ipp.KEYWORD('two-sided-long-edge'),
    ],
    input_source_supported = [
        ipp.KEYWORD('adf'),
        ipp.KEYWORD('platen'),
    ],
    ipp_features_supported = [
        ipp.KEYWORD('none'),
    ],
    ipp_versions_supported = [
        ipp.KEYWORD('2.0'),
    ],
    job_ids_supported = ipp.BOOLEAN(True),
    multiple_document_handling_supported = [
        ipp.KEYWORD('single-document'),
    ],
    multiple_document_jobs_supported = ipp.BOOLEAN(False),
    natural_language_configured = ipp.LANGUAGE('en-us'),
    operations_supported = [
        ipp.OP.GET_PRINTER_ATTRIBUTES,
        ipp.OP.GET_JOBS,
        ipp.OP.GET_JOB_ATTRIBUTES,
        ipp.OP.CREATE_JOB,
        ipp.OP.GET_NEXT_DOCUMENT_DATA,
        ipp.OP.CANCEL_JOB,
    ],
    output_attributes_default = ipp.COLLECTION(
        noise_removal = ipp.INTEGER(0),
        output_compression_quality_factor = ipp.INTEGER(80),
    ),
    output_attributes_supported = [
        ipp.KEYWORD('noise-removal'),
        ipp.KEYWORD('output-compression-quality-factor'),
    ],
    printer_device_id = ipp.TEXT('MFG:OpenPrinting;MDL:Virtual IPP Scanner;CLS:SCANNER;CMD:JPEG,PNG'),
    printer_geo_location = ipp.UNKNOWN(),
    printer_get_attributes_supported = [
        ipp.KEYWORD('charset-configured'),
        ipp.KEYWORD('charset-supported'),
        ipp.KEYWORD('color-supported'),
        ipp.KEYWORD('compression-supported'),
        ipp.KEYWORD('copies-default'),
        ipp.KEYWORD('copies-supported'),
        ipp.KEYWORD('document-format-default'),
        ipp.KEYWORD('document-format-supported'),
        ipp.KEYWORD('generated-natural-language-supported'),
        ipp.KEYWORD('input-attributes-default'),
        ipp.KEYWORD('input-attributes-supported'),
        ipp.KEYWORD('input-color-mode-supported'),
        ipp.KEYWORD('input-media-supported'),
        ipp.KEYWORD('input-orientation-requested-supported'),
        ipp.KEYWORD('input-quality-supported'),
        ipp.KEYWORD('input-resolution-supported'),
        ipp.KEYWORD('input-sides-supported'),
        ipp.KEYWORD('input-source-supported'),
        ipp.KEYWORD('ipp-features-supported'),
        ipp.KEYWORD('ipp-versions-supported'),
        ipp.KEYWORD('job-ids-supported'),
        ipp.KEYWORD('multiple-document-handling-supported'),
        ipp.KEYWORD('multiple-document-jobs-supported'),
        ipp.KEYWORD('natural-language-configured'),
        ipp.KEYWORD('operations-supported'),
        ipp.KEYWORD('output-attributes-default'),
        ipp.KEYWORD('output-attributes-supported'),
        ipp.KEYWORD('printer-device-id'),
        ipp.KEYWORD('printer-geo-location'),
        ipp.KEYWORD('printer-get-attributes-supported'),
        ipp.KEYWORD('printer-location'),
        ipp.KEYWORD('printer-make-and-model'),
        ipp.KEYWORD('printer-name'),
        ipp.KEYWORD('printer-organization'),
        ipp.KEYWORD('printer-organizational-unit'),
        ipp.KEYWORD('which-jobs-supported'),
    ],
    printer_location = ipp.TEXT(''),
    printer_make_and_model = ipp.TEXT('OpenPrinting Virtual IPP Scanner'),
    printer_name = ipp.NAME('VIPP123456789'),
    printer_organization = ipp.TEXT(''),
    printer_organizational_unit = ipp.TEXT(''),
    which_jobs_supported = [
        ipp.KEYWORD('completed'),
        ipp.KEYWORD('not-completed'),
    ],
)

# DNS-SD parameters
dnssd.device = dnssd.Device(
    instance = 'OpenPrinting Virtual IPP Scanner',
    UUID = UUID('f38bbb71-3efa-4c8e-86d6-2b067a94cef1'),
    services = [
               dnssd.Service(
            types = [
                '_ipp._tcp',
                '_ipps._tcp',
            ],
            TXT = [
                'txtvers=1',
                'air=none',
                'UUID=f38bbb71-3efa-4c8e-86d6-2b067a94cef1',
                'DUUID=f38bbb71-3efa-4c8e-86d6-2b067a94cef1',
                'TLS=1.2',
                'ty=OpenPrinting Virtual IPP Scanner',
                "rs=ipp/scan",
            ],
            endpoints = [
                'ipp://192.168.1.100',
                'ipps://192.168.1.100',
                'ipp://[fe80::ce64:1aff:fe71:e2d0]',
                'ipps://[fe80::ce64:1aff:fe71:e2d0]',
            ],
        ),

    ],
)
